import { ProjectCardProps } from "@/types/types";

export const projects: Omit<ProjectCardProps, 'index'>[] = [
    {
       name: "Ecosystem QVMD",
       descriptionKey: "ecosystemQVMD",
       tags: [
          { name: "ANGULAR", color: "dark:text-[--primary-color]" },
          { name: "TYPESCRIPT", color: "dark:text-[--primary-color]" },
          { name: "C#", color: "dark:text-[--primary-color]" },
          { name: ".NET", color: "dark:text-[--primary-color]" },
          { name: "AWS", color: "dark:text-[--primary-color]" },
          { name: "POSTGRESQL", color: "dark:text-[--primary-color]" },
          { name: "SWAGGER", color: "dark:text-[--primary-color]" },
          { name: "JASMINE", color: "dark:text-[--primary-color]" },
          { name: "XUNIT", color: "dark:text-[--primary-color]" },
          { name: "AZURE DEV OPS", color: "dark:text-[--primary-color]" },
          { name: "DOCKER", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/ecosystem-qvmd.png",
       video: "",
       sourceWeb: "https://www.quiveutmesdechets.fr/",
       sourceGithub: "",
       learnMore: "",
       projectSlug: "ecosystem-qvmd",
    },
    {
       name: "Make Sense",
       descriptionKey: "makeSense",
       tags: [
          { name: "REACTJS", color: "dark:text-[--primary-color]" },
          { name: "VITEJS", color: "dark:text-[--primary-color]" },
          { name: "NODEJS", color: "dark:text-[--primary-color]" },
          { name: "EXPRESS", color: "dark:text-[--primary-color]" },
          { name: "MYSQL", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/makesense2.png",
       video: "",
       sourceWeb: "https://make-sense.davyrobert.fr",
       sourceGithub: "https://github.com/DavyR01/Make_Sense_Project",
       projectSlug: "makesense",
    },
    {
       name: "Wild Rent",
       descriptionKey: "wildRent",
       tags: [
          { name: "NEXTJS", color: "dark:text-[--primary-color]" },
          { name: "TYPESCRIPT", color: "dark:text-[--primary-color]" },
          { name: "TAILWINDCSS", color: "dark:text-[--primary-color]" },
          { name: "GRAPHQL", color: "dark:text-[--primary-color]" },
          { name: "APOLLO", color: "dark:text-[--primary-color]" },
          { name: "JEST", color: "dark:text-[--primary-color]" },
          { name: "PLAYWRIGHT", color: "dark:text-[--primary-color]" },
          { name: "POSTGRESQL", color: "dark:text-[--primary-color]" },
          { name: "SQLITE", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/wildrent.png",
       video: "",
       sourceWeb: "https://wildrent.davyrobert.fr/",
       sourceGithub: "https://github.com/DavyR01/Wild-rent-myRepo",
       projectSlug: "wildrent",
    },
    {
       name: "MyCrit Job",
       descriptionKey: "myCrit",
       tags: [
          { name: "JAVA", color: "dark:text-[--primary-color]" },
          { name: "KOTLIN", color: "dark:text-[--primary-color]" },
          { name: "ANDROID STUDIO", color: "dark:text-[--primary-color]" },
          { name: "FIREBASE", color: "dark:text-[--primary-color]" },
          { name: "SQLITE", color: "dark:text-[--primary-color]" },
          { name: "JIRA", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/crit_job5.png",
       video: "",
       sourceWeb: "",
       projectSlug: "crit-job",
       learnMore: "https://play.google.com/store/apps/details?id=com.critjob.mycrit&hl=fr&pli=1"
    },
    {
       name: "Eurowatt Super7",
       descriptionKey: "eurowatt",
       tags: [
          { name: "PHP", color: "dark:text-[--primary-color]" },
          { name: "SYMFONY", color: "dark:text-[--primary-color]" },
          { name: "AZURE DEV OPS", color: "dark:text-[--primary-color]" },
          { name: "POSTGRESQL", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/super7_interface.png",
       video: "",
       sourceWeb: "",
       projectSlug: "eurowatt-super7",
       learnMore: "https://eurowatt.com/en"
    },
    {
       name: "Virtual Met'Art",
       descriptionKey: "virtuelMetArt",
       tags: [
          { name: "REACTJS", color: "dark:text-[--primary-color]" },
          { name: "VITEJS", color: "dark:text-[--primary-color]" },
          { name: "TAILWINDCSS", color: "dark:text-[--primary-color]" },
          { name: "REST API", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/virtual_met_art.png",
       video: "",
       sourceWeb: "https://virtual-met-art01.davyrobert.fr",
       sourceGithub: "https://github.com/DavyR01/Virtual-MET-ART",
       projectSlug: "virtual-met-art",
    },
    {
       name: "France Trivia",
       descriptionKey: "franceTrivia",
       tags: [
          { name: "JAVASCRIPT", color: "dark:text-[--primary-color]" },
          { name: "HTML", color: "dark:text-[--primary-color]" },
          { name: "CSS", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/france_trivia.png",
       video: "",
       sourceWeb: "https://france-trivia.davyrobert.fr/",
       sourceGithub: "https://github.com/DavyR01/Projet-P1-WCS",
       projectSlug: "france-trivia",
    },
    {
       name: "Blog Project JS",
       descriptionKey: "blogProject",
       tags: [
          { name: "JAVASCRIPT", color: "dark:text-[--primary-color]" },
          { name: "SCSS", color: "dark:text-[--primary-color]" },
          { name: "NODEJS", color: "dark:text-[--primary-color]" },
          { name: "WEBPACK", color: "dark:text-[--primary-color]" },
          { name: "REST API", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/blog_project.png",
       video: "",
       sourceWeb: "https://my-blog-project.davyrobert.fr/",
       sourceGithub: "https://github.com/DavyR01/Javascript_Blog_Project/tree/main",
       projectSlug: "blog-project-js",
    },
    {
       name: "Louis Vuitton",
       descriptionKey: "louisVuitton",
       tags: [
          { name: "REACT JS", color: "dark:text-[--primary-color]" },
          { name: "SHAREPOINT", color: "dark:text-[--primary-color]" },
          { name: "WEBPPACK", color: "dark:text-[--primary-color]" },
          { name: "NODEJS", color: "dark:text-[--primary-color]" },
          { name: "JEST", color: "dark:text-[--primary-color]" },
       ],
       image: "/projects/vuitton2.png",
       video: "",
       sourceWeb: "",
       projectSlug: "louisvuitton",
       learnMore: "https://fr.louisvuitton.com/fra-fr/homepage"
    },
 ];