// "use client"

import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "My portfolio",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const isMaintenanceMode = process.env.APP_MAINTENANCE === "true";
   return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
         <body className="antialiased flex flex-col min-h-screen overflow-x-hidden">            {isMaintenanceMode ? (
            <div className="h-screen flex justify-center items-center font-medium text-3xl text-center text-white bg-[#1A1A1A]">
               <div className="border border-[#5EE9B5] text-[#5EE9B5] p-16">Le site est actuellement en cours d&apos;élaboration. <br /> Veuillez patienter...............</div>
            </div>
         ) : (
            <>
               <Navbar />
               <main className="flex-1 pt-20">
                  {children}
               </main>
               <Footer />
            </>
         )}
         </body>
      </html>
   );
}
