// "use client"

import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./components/Footer";
import { getServerThemeClass, THEME_INIT_SCRIPT } from "@/utils/theme";
import Script from "next/script";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import ThemeToggle from "./components/ThemeToggle";

const geistSans = localFont({
   src: "../fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "../fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Davy Robert - Portfolio",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const isMaintenanceMode = process.env.APP_MAINTENANCE === "false";
   const htmlThemeClass = await getServerThemeClass();
   return (
      <html lang="en" className={`${htmlThemeClass} ${geistSans.variable} ${geistMono.variable}`}>
         <body className="antialiased flex flex-col min-h-screen overflow-x-hidden bg-white dark:bg-black">
            <Script id="theme-init" strategy="beforeInteractive">
               {THEME_INIT_SCRIPT}
            </Script>
            <ThemeProvider>
               {isMaintenanceMode ? (
                  <div className="h-screen flex justify-center items-center font-medium text-3xl text-center dark:bg-black dark:text-white">
                     <div className="border border-[--primary-color] text-[--primary-color] p-16">Le site est actuellement en cours d&apos;élaboration. <br /> Veuillez patienter...............</div>
                  </div>
               ) : (
                  <>
                     <Navbar />
                     <main className="flex-1 pt-20">
                        {children}
                     </main>
                     <Footer />
                     <ThemeToggle />
                  </>
               )}
            </ThemeProvider>
         </body>
      </html>
   );
}
